#  App Engine アプリの設定
#  アプリのコード、Node.js ランタイム、環境変数に関する情報
# https://cloud.google.com/appengine/docs/standard/nodejs/building-app/deploying-web-service?hl=ja
# 上書きできないランタイム環境変数のリスト
# https://cloud.google.com/appengine/docs/standard/nodejs/runtime?hl=ja#environment_variables

runtime: nodejs12
instance_class: F1
# instance_class: B1

# manual_scaling:
#   instances: 1

# basic_scaling:
#   max_instances: 1
# idle_timeout:  2m

includes:
  - secret.yaml
